import { BlogPost } from '@/types';

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: '10 Daily Habits for Healthy Skin',
    slug: '10-daily-habits-healthy-skin',
    excerpt: 'Discover dermatologist-approved daily habits to maintain radiant, healthy skin all year round.',
    content: 'Healthy skin starts with consistent daily habits recommended by dermatologists. Here are our top 10 tips: 1. Always apply broad-spectrum SPF 30+ sunscreen, 2. Cleanse gently twice daily, 3. Moisturize immediately after washing, 4. Stay hydrated — drink 8 glasses of water, 5. Eat an antioxidant-rich diet, 6. Avoid touching your face, 7. Change pillowcases regularly, 8. Manage stress with mindfulness, 9. Get 7–8 hours of quality sleep, 10. Schedule annual full-body skin check-ups.',
    author: 'Dr. Priya Sharma',
    date: '2024-01-15',
    category: 'Skin Health',
    image: 'https://images.unsplash.com/photo-1554050857-c84a8abdb5e5?auto=format&fit=crop&q=80&w=800',
    readTime: '5 min read',
  },
  {
    id: 2,
    title: 'Understanding Acne: Causes, Types & Treatments',
    slug: 'understanding-acne-causes-treatments',
    excerpt: 'A comprehensive guide to understanding acne and the most effective medical treatments available.',
    content: 'Acne is one of the most common skin conditions affecting millions worldwide. It occurs when hair follicles become clogged with oil and dead skin cells. Types include whiteheads, blackheads, papules, pustules, nodules, and cysts. Medical treatments range from topical retinoids, benzoyl peroxide, and salicylic acid to oral antibiotics, hormonal therapy, and isotretinoin for severe cases. Advanced clinical options include chemical peels, laser therapy, and corticosteroid injections. Always consult a board-certified dermatologist for a personalized treatment plan.',
    author: 'Dr. Arjun Mehta',
    date: '2024-01-10',
    category: 'Acne Treatment',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=800',
    readTime: '6 min read',
  },
  {
    id: 3,
    title: 'Sun Protection: Why SPF Is Non-Negotiable',
    slug: 'sun-protection-spf-guide',
    excerpt: 'Everything you need to know about sunscreen, UV damage, and protecting your skin from skin cancer.',
    content: 'UV radiation is the leading cause of premature skin aging and skin cancer. Dermatologists universally recommend daily sunscreen use, even on cloudy days and indoors near windows. Choose a broad-spectrum SPF 30 or higher, apply generously 15 minutes before sun exposure, and reapply every 2 hours. Physical sunscreens containing zinc oxide or titanium dioxide are ideal for sensitive skin. Pair sunscreen with protective clothing, wide-brimmed hats, and UV-blocking sunglasses for comprehensive protection. Annual skin checks are vital for early detection of melanoma and other skin cancers.',
    author: 'Dr. Nisha Kapoor',
    date: '2024-01-05',
    category: 'Sun Care',
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=800',
    readTime: '4 min read',
  },
  {
    id: 4,
    title: 'Anti-Aging Dermatology: What Really Works',
    slug: 'anti-aging-dermatology',
    excerpt: 'A dermatologist\'s guide to the most scientifically proven anti-aging treatments and skincare ingredients.',
    content: 'The anti-aging skincare market is saturated with claims, but dermatologists rely on science-backed ingredients and procedures. Retinoids (vitamin A derivatives) remain the gold standard for reducing fine lines, wrinkles, and improving skin texture. Vitamin C serums provide powerful antioxidant protection. Hyaluronic acid delivers deep hydration. In-clinic treatments include botulinum toxin (Botox) for dynamic wrinkles, dermal fillers for volume restoration, fractional laser resurfacing, microneedling with PRP, and chemical peels. The best anti-aging approach combines medical-grade skincare with clinical treatments tailored to your skin\'s specific aging pattern.',
    author: 'Dr. Priya Sharma',
    date: '2024-01-20',
    category: 'Anti-Aging',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=800',
    readTime: '6 min read',
  },
];
