import { Service } from '@/types';

export const services: Service[] = [
  {
    id: 1,
    name: 'Acne & Scar Treatment',
    slug: 'acne-scar-treatment',
    category: 'Medical Dermatology',
    description: 'Comprehensive acne diagnosis and advanced treatment to clear breakouts and minimize scarring permanently.',
    price: 60,
    duration: 45,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800',
    benefits: [
      'Personalized skin analysis',
      'Medical-grade topical treatments',
      'Laser or chemical peel options',
      'Long-term clear-skin strategy',
    ],
  },
  {
    id: 2,
    name: 'Laser Skin Resurfacing',
    slug: 'laser-skin-resurfacing',
    category: 'Cosmetic Dermatology',
    description: 'FDA-approved fractional laser treatment to reduce wrinkles, sun damage, scars, and uneven skin tone.',
    price: 200,
    duration: 60,
    image: 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&q=80&w=800',
    benefits: [
      'Stimulates collagen production',
      'Reduces fine lines and wrinkles',
      'Improves skin texture and tone',
      'Minimal downtime',
    ],
  },
  {
    id: 3,
    name: 'Botox & Dermal Fillers',
    slug: 'botox-dermal-fillers',
    category: 'Cosmetic Dermatology',
    description: 'Expert administration of botulinum toxin and hyaluronic acid fillers for natural-looking facial rejuvenation.',
    price: 300,
    duration: 45,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800',
    benefits: [
      'Smooths dynamic wrinkles',
      'Restores facial volume',
      'Non-surgical and quick',
      'Results last 6–12 months',
    ],
  },
  {
    id: 4,
    name: 'PRP Hair Loss Therapy',
    slug: 'prp-hair-loss-therapy',
    category: 'Hair Dermatology',
    description: 'Platelet-Rich Plasma (PRP) therapy to stimulate hair follicles, reduce hair loss, and promote natural regrowth.',
    price: 180,
    duration: 60,
    image: 'https://images.unsplash.com/photo-1519782509177-3e110dc5222b?auto=format&fit=crop&q=80&w=800',
    benefits: [
      'Uses your body\'s own growth factors',
      'Stimulates dormant hair follicles',
      'Safe with minimal side effects',
      'Visible results in 3–6 sessions',
    ],
  },
  {
    id: 5,
    name: 'Skin Cancer Screening',
    slug: 'skin-cancer-screening',
    category: 'Medical Dermatology',
    description: 'Full-body mole mapping and skin cancer screening using dermoscopy for early detection and peace of mind.',
    price: 120,
    duration: 60,
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
    benefits: [
      'Full-body dermoscopic exam',
      'Digital mole mapping',
      'Early melanoma detection',
      'Biopsy if required',
    ],
  },
  {
    id: 6,
    name: 'Chemical Peel & Brightening',
    slug: 'chemical-peel-brightening',
    category: 'Cosmetic Dermatology',
    description: 'Medical-grade chemical peels to exfoliate, brighten, and renew skin tone and texture for a radiant complexion.',
    price: 150,
    duration: 75,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
    benefits: [
      'Exfoliates dead skin cells',
      'Reduces pigmentation & dark spots',
      'Improves skin clarity and glow',
      'Customized peel depth',
    ],
  },
];
